server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filters: stat,wall,log4j

  redis:
      database: 0
      host: 116.62.65.65
      port: 6379
      password: Icoachu2017
      jedis:
        pool:
          max-active: 200
          max-wait: -1
          max-idle: 10
          min-idle: 0
      timeout: 1000

mybatis:
  mapper-locations: classpath*:com/xjl/mapper/*/*.xml
  type-aliases-package: com.xjl.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

